### ISSUE TITLE
Partitions created in the past

### ISSUE THREAD

**Issue by ylegat** [qonto/postgresql-partition-manager#38]
### Describe the bug

When provisioning partitions for the first time, the manager will create a number of partitions in the past equal to the retention value.

For instance, with the following configuration:
```yaml
partitions:
  partitioned_table:
    schema: public
    table: partitioned_table
    partitionKey: partition_key
    interval: monthly
    retention: 60
    preProvisioned: 3
    cleanupPolicy: detach
```
The manager will create 60 partitions, from `partitioned_table_2019_08` to `partitioned_table_2024_08` (plus 3 pre provisioned partitions, which is expected) (note: the provisioning was run on 08/24).

### Desktop (please complete the following information)

- OS: Linux
- PostgreSQL partition manager: 0.1.0
- PostgreSQL version: 14.10
- Partition key column type: uuidv7

### To Reproduce

Configure a partitioned table with retention > 0, provision the partitions using the manager and check if partitions were created in the past.

### Expected behavior

I would expect past partitions not to be created by the manager.

### Additional context

None
